# coding: utf-8

"""
    MailSlurp API

    MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository  # noqa: E501

    The version of the OpenAPI document: 6.5.2
    Contact: contact@mailslurp.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mailslurp_client
from mailslurp_client.api.connector_controller_api import ConnectorControllerApi  # noqa: E501
from mailslurp_client.rest import ApiException


class TestConnectorControllerApi(unittest.TestCase):
    """ConnectorControllerApi unit test stubs"""

    def setUp(self):
        self.api = mailslurp_client.api.connector_controller_api.ConnectorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_connector(self):
        """Test case for create_connector

        Create an inbox connector  # noqa: E501
        """
        pass

    def test_delete_all_connector(self):
        """Test case for delete_all_connector

        Delete all inbox connectors  # noqa: E501
        """
        pass

    def test_delete_connector(self):
        """Test case for delete_connector

        Delete an inbox connector  # noqa: E501
        """
        pass

    def test_get_all_connector_sync_events(self):
        """Test case for get_all_connector_sync_events

        Get all inbox connector sync events  # noqa: E501
        """
        pass

    def test_get_connector(self):
        """Test case for get_connector

        Get an inbox connector  # noqa: E501
        """
        pass

    def test_get_connector_sync_event(self):
        """Test case for get_connector_sync_event

        Get an inbox connector sync event  # noqa: E501
        """
        pass

    def test_get_connector_sync_events(self):
        """Test case for get_connector_sync_events

        Get an inbox connector sync events  # noqa: E501
        """
        pass

    def test_get_connectors(self):
        """Test case for get_connectors

        Get inbox connectors  # noqa: E501
        """
        pass

    def test_sync_connector(self):
        """Test case for sync_connector

        Sync an inbox connector  # noqa: E501
        """
        pass

    def test_update_connector(self):
        """Test case for update_connector

        Update an inbox connector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
