# coding: utf-8

"""
    MailSlurp API

    For documentation see [developer guide](https://www.mailslurp.com/developers). [Create an account](https://app.mailslurp.com) in the MailSlurp Dashboard to [view your API Key](https://app). For all bugs, feature requests, or help please [see support](https://www.mailslurp.com/support/).  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    Contact: contact@mailslurp.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mailslurp_client
from mailslurp_client.api.extra_operations_api import ExtraOperationsApi  # noqa: E501
from mailslurp_client.rest import ApiException


class TestExtraOperationsApi(unittest.TestCase):
    """ExtraOperationsApi unit test stubs"""

    def setUp(self):
        self.api = mailslurp_client.api.extra_operations_api.ExtraOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_create_inboxes(self):
        """Test case for bulk_create_inboxes

        Bulk create Inboxes (email addresses)  # noqa: E501
        """
        pass

    def test_bulk_delete_inboxes(self):
        """Test case for bulk_delete_inboxes

        Bulk Delete Inboxes  # noqa: E501
        """
        pass

    def test_bulk_send_emails(self):
        """Test case for bulk_send_emails

        Bulk Send Emails  # noqa: E501
        """
        pass

    def test_create_inbox(self):
        """Test case for create_inbox

        Create an Inbox (email address)  # noqa: E501
        """
        pass

    def test_create_webhook(self):
        """Test case for create_webhook

        Attach a WebHook URL to an inbox  # noqa: E501
        """
        pass

    def test_delete_email(self):
        """Test case for delete_email

        Delete Email  # noqa: E501
        """
        pass

    def test_delete_inbox(self):
        """Test case for delete_inbox

        Delete Inbox / Email Address  # noqa: E501
        """
        pass

    def test_delete_webhook(self):
        """Test case for delete_webhook

        Delete and disable a WebHook for an Inbox  # noqa: E501
        """
        pass

    def test_download_attachment(self):
        """Test case for download_attachment

        Get email attachment  # noqa: E501
        """
        pass

    def test_get_email(self):
        """Test case for get_email

        Get Email Content  # noqa: E501
        """
        pass

    def test_get_emails(self):
        """Test case for get_emails

        List Emails in an Inbox / EmailAddress  # noqa: E501
        """
        pass

    def test_get_inbox(self):
        """Test case for get_inbox

        Get Inbox / EmailAddress  # noqa: E501
        """
        pass

    def test_get_inboxes(self):
        """Test case for get_inboxes

        List Inboxes / Email Addresses  # noqa: E501
        """
        pass

    def test_get_raw_email_contents(self):
        """Test case for get_raw_email_contents

        Get Raw Email Content  # noqa: E501
        """
        pass

    def test_get_webhooks(self):
        """Test case for get_webhooks

        Get all WebHooks for an Inbox  # noqa: E501
        """
        pass

    def test_send_email(self):
        """Test case for send_email

        Send Email  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
