# coding: utf-8

"""
    MailSlurp API

    MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository  # noqa: E501

    The version of the OpenAPI document: 6.5.2
    Contact: contact@mailslurp.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mailslurp_client
from mailslurp_client.models.page_email_thread_projection import PageEmailThreadProjection  # noqa: E501
from mailslurp_client.rest import ApiException

class TestPageEmailThreadProjection(unittest.TestCase):
    """PageEmailThreadProjection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PageEmailThreadProjection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mailslurp_client.models.page_email_thread_projection.PageEmailThreadProjection()  # noqa: E501
        if include_optional :
            return PageEmailThreadProjection(
                content = [
                    mailslurp_client.models.email_thread_projection.EmailThreadProjection(
                        sender = mailslurp_client.models.sender_projection.SenderProjection(
                            email_address = '0', 
                            raw_value = '0', 
                            name = '0', ), 
                        recipients = mailslurp_client.models.email_recipients_projection.EmailRecipientsProjection(
                            to = [
                                mailslurp_client.models.recipient_projection.RecipientProjection(
                                    email_address = '0', 
                                    raw_value = '0', 
                                    name = '0', )
                                ], 
                            cc = [
                                mailslurp_client.models.recipient_projection.RecipientProjection(
                                    email_address = '0', 
                                    raw_value = '0', 
                                    name = '0', )
                                ], 
                            bcc = [
                                mailslurp_client.models.recipient_projection.RecipientProjection(
                                    email_address = '0', 
                                    raw_value = '0', 
                                    name = '0', )
                                ], ), 
                        user_id = '0', 
                        inbox_id = '0', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        to = [
                            '0'
                            ], 
                        cc = [
                            '0'
                            ], 
                        bcc = [
                            '0'
                            ], 
                        has_attachments = True, 
                        unread = True, 
                        message_count = 56, 
                        last_body_excerpt = '0', 
                        last_text_excerpt = '0', 
                        last_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_from = '0', 
                        last_sender = mailslurp_client.models.sender_projection.SenderProjection(
                            email_address = '0', 
                            raw_value = '0', 
                            name = '0', ), 
                        subject = '0', 
                        id = '0', 
                        from = '0', )
                    ], 
                pageable = mailslurp_client.models.pageable_object.PageableObject(
                    page_size = 56, 
                    paged = True, 
                    page_number = 56, 
                    unpaged = True, 
                    offset = 56, 
                    sort = mailslurp_client.models.sort_object.SortObject(
                        sorted = True, 
                        unsorted = True, 
                        empty = True, ), ), 
                total_elements = 56, 
                total_pages = 56, 
                last = True, 
                number_of_elements = 56, 
                first = True, 
                size = 56, 
                number = 56, 
                sort = mailslurp_client.models.sort_object.SortObject(
                    sorted = True, 
                    unsorted = True, 
                    empty = True, ), 
                empty = True
            )
        else :
            return PageEmailThreadProjection(
                total_elements = 56,
                total_pages = 56,
        )

    def testPageEmailThreadProjection(self):
        """Test PageEmailThreadProjection"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
